### ISSUE TITLE
ReplaySession.cc:127: void ReplaySession::copy_state_to(Session&, EmuFs&): Assertion `!vm->has_breakpoints()' failed

### ISSUE THREAD

**Issue by heycam** [mozilla/rr#1422]
I get this assertion when I try to replay this particular recording with a conditional breakpoint set.  I then immediately see:

    /build/buildd/gdb-7.7.1/gdb/thread.c:85: internal-error: inferior_thread: Assertion `tp' failed.

at which point gdb wants to quit.

**Comment by rocallahan** [comment]
What's your conditional breakpoint?

**Comment by heycam** [comment]
It was `b RestyleManager.cpp:3950 if entry.mStyleContext->mFrameRefCnt==0` where `entry.mStyleContext` is an `nsRefPtr` and thus would have been calling `operator->`.  This is with a local patch so you won't be able to set that yourself. A "complicated" expression like dereferencing an `nsRefPtr` might be enough to reproduce though.

**Comment by rocallahan** [comment]
I'll try. FWIW, things will be a lot faster if you avoid function calls in breakpoint conditions, e.g. by writing mStyleContext.mRawPtr->

**Comment by heycam** [comment]
Yes I was noticing playback being slow. I will remember to manually go through mRawPtr in the future.

**Comment by rocallahan** [comment]
Yeah, I can reproduce this easily.

**Comment by rocallahan** [comment]
Fixing the breakpoint assertion is easy; it's simple enough to clone breakpoints when we clone a session.

Now I run into a problem of resource exhaustion. We don't clean up dead DiversionSessions very well; the processes live forever. They get `SIGKILL` and `PTRACE_DETACH`, but then they're zombies; if we avoid marking the Tasks as unstable_exit, we still fail to reap the zombie because `waitpid` fails because the task is not our child --- which is because, apart from ptrace, the true parent of a diversion Task is the replay Task we cloned it from.

**Comment by rocallahan** [comment]
Fixed that, and we hit another bug of course :-).

gdb tries to move past a breakpoint by removing all breakpoints and then singlestepping. Unfortunately, if we've just created a diversion session to evaluate the breakpoint condition, "removing all the breakpoints" happens in the diversion session; then we continue, which switches from the diversion session to the replay session, in which all the breakpoints are still present!

This requires improved heuristics. Need to think on it.
