### ISSUE TITLE
Support Intel Penryn

### ISSUE THREAD

**Issue by dfc** [mozilla/rr#1474]
I did not find an open or closed ticket for this. I apologize if there are architectural constraints. 

Can support for Penryn CPUs be added?

**Comment by rocallahan** [comment]
Check out http://web.eece.maine.edu/~vweaver/projects/deterministic/deterministic_counters.pdf. I'm not 100% sure but it appears Penryn is "Core 2" in that paper, and according to that work there isn't a deterministic performance counter we can use. To support Penryn someone would have to show otherwise...

**Comment by hotsphink** [comment]
My Penryn CPU's /proc/cpuinfo has:

  model name	: Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz

which makes it sound like a Core 2.

**Comment by rocallahan** [comment]
In that case, Penryn will not work unless Vince's information is wrong. If someone with a Penryn gets rr working on it, we'd take a patch, but otherwise I'll assume it's impossible.
