### ISSUE TITLE
Support for setgid call

### ISSUE THREAD

**Issue by BenjaminSchubert** [mozilla/rr#1476]
I've been running Apache's httpd under rr as a user for now. However, I would need it to run it as root for some experiments and I'm hitting an "Expected ENOSYS for 'setgid' but got result 0; execution of syscall unsupported by rr". 

I know #1053 mentions it, but I would like to know if it would be possible to implement it ?

Thanks a lot

**Comment by rocallahan** [comment]
It would be trivial to support `setgid`. The only nontrivial part would be writing a testcase. Want to have a go?

**Comment by BenjaminSchubert** [comment]
Sure ! I will look at it. In which files should I add these ? Is there any documentation on how to do it ?

Thanks !

**Comment by rocallahan** [comment]
Look at a32f60fdaaf3b3c558989005ae33b4c13a835793 to see how I added support for some syscalls there.

Writing a testcase for this is a bit tricky because we want our tests to work when not run as root. I think you can do this by following the `unshare.c` test and entering a new user namespace before you do `setgid`.
