### ISSUE TITLE
replaying in the debugger should not allow the tracee to exit

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1490]
When debugging a replay it would be nice to be able to say:
 continue
[wait for execution to get to end of replay]
 break some_function
 rc

to get to the last execution of some_function before the program exited. However at the moment you can't do that because the forward-continue allows the tracee to exit, and then gdb prints "[Inferior 1 (process 27144) exited normally]" and "rc" complains "The program is not being run".

**Comment by pm215** [comment]
Similarly, a reverse-continue off the start of the replay shouldn't terminate the tracee either.

**Comment by rocallahan** [comment]
Terminating the tracee at the end of forward execution is what gdb normally does, and by default we preserved normal gdb behavior. I made it terminate when reverse execution reaches the start for the sake of symmetry. But I see your point and I agree that with reverse execution available it makes a lot more sense to just break at the start or end instead of terminating. Let's do that.

**Comment by rocallahan** [comment]
Thanks for filing all these issues, by the way. This is really helping make rr better.

**Comment by mstange** [comment]
I hit this exact problem just now. My first intuition was to try "reverse-run", but it seems that's not a valid command. :-)

**Comment by rocallahan** [comment]
https://github.com/mozilla/rr/commit/c562951d67de4dc718f71af3f6ddaf04331a1955 fixes this for reverse execution.
