### ISSUE TITLE
conditional bp/wp in reverse-execution unusably slow: would implementing remote conditional bps help?

### ISSUE THREAD

**Issue by pm215** [mozilla/rr#1493]
Conditional breakpoints and watchpoints in reverse execution seem to be unusably slow: in the replay I'm trying to debug (total execution time a minute or so) a forward-conditional-bp is fine but a reverse-conditional-bp takes so close to "forever" to halt that I haven't yet had the patience to see if it will ever actually stop and return control to gdb.

The gdb remote protocol includes the option for evaluation of conditional bp/wp expressions on the target (feature "ConditionalBreakpoints" in the qSupported check), but rr doesn't currently seem to implement it. Would being able to determine whether the cond-bp had hit within rr without having to hand control back to gdb improve performance here? (For instance you could execute forward to find all the conditional-bp-hit points within a section of the replay and then just go to the last one.)

**Comment by rocallahan** [comment]
Yes, implementing the gdb ConditionalBreakpoints feature would really help. I've been holding off on that until we had a real case where it matters, and Mozilla users haven't hit it AFAIK, but it sounds like you have one. You could enable logging in ReplayTimeline.cc to confirm (you'd see a single `reverse-continue` command turn into a vast number of `ReplayTimeline::reverse_continue` calls).

I was thinking maybe we should release 4.0 without this, but since you've hit it already maybe I should just bite the bullet and do it. It's probably not hard. Though, can you check that gdb can actually pass your conditions to the target? You could add `ConditionalBreakpoints` to the feature list in `GdbConnection::query`, enable logging in `GdbConnection` then try setting one; we'll assert, but you should see the gdb command go across.

**Comment by rocallahan** [comment]
(I get the impression from reading the docs that there are some fairly arbitrary limits on what can be handled on the target, but I don't know what they are. Conditions involving function calls can't be handled for obvious reasons.)

**Comment by pm215** [comment]
Enabling logging in ReplayTimeline shows that it is doing a lot of reverse_continue calls, yes. I assume the problem happens with conditional breakpoints which have a low condition-passed rate. (The kind of thing I'm doing in QEMU is "conditional breakpoint on JITting for guest address X", where we'll JIT lots of basic blocks that aren't the one we want before reaching the one the condbp will fire on.)

Claiming ConditionalBreakpoints as supported does indeed cause gdb to use the feature; for instance for `break gen_intermediate_code_internal if (tb->flags >> 28) == 0` we get
```
[GdbConnection] raw request Z(0,5555557632c2,1;X1e,26000622100223fe901610021a2208021a221c2a400b2a4022002a401327)
```

Looking through the gdb source code and the docs, the most obvious limitation is that all arithmetic in the conditions has to be integer (or boolean); floating point isn't supported.

**Comment by rocallahan** [comment]
Thanks for checking that! I guess we should just implement this.

> The kind of thing I'm doing in QEMU is "conditional breakpoint on JITting for guest address X"

FWIW have you tried setting a read watchpoint on the memory location holding guest address X?

**Comment by pm215** [comment]
That would be possible in theory, but in practice not so easy, because you would need to know the guest physical address for the virtual guest PC, which of course isn't known until the kernel sets up the page tables for that process (and even then you need to manually do a page table walk in guest memory to find the mapping, which is pretty tedious). I agree that for the moment trying to find ways of phrasing what you want to do that involve unconditional bps and wps is going to be the best approach, though.

(The cond bp example in my previous comment is "stop when we translate code for userspace", incidentally.)

**Comment by rocallahan** [comment]
I have remote expression evaluation working. In a simple test it improves performance astronomically. Unfortunately I discovered https://sourceware.org/bugzilla/show_bug.cgi?id=18617 :-(. The obvious workaround is to disable remote evaluation of all expressions containing `ext` and `zero_ext` bytecodes, but even simple stuff like
````
int var;
(gdb) cond 1 var==-1
````
generates `ext`, which makes this feature much less useful.

**Comment by rocallahan** [comment]
Actually there is an insane workaround I could use. When we see `ext`/`zero_ext`, assume the correct operand could be any of 8, 16, 32 or 64 which are <= the given operand, fork the interpreter state to evaluate all of those possibilities, and if all forks give the same answer, return that as the correct answer, otherwise fail.
