### ISSUE TITLE
execve makes replay unportable. doesn’t use hardlink

### ISSUE THREAD

**Issue by bgirard** [mozilla/rr#1518]
Working on RROrangeHunter I noticed that moving a directory containing the replay + binaries doesn't allow replaying.

However after the directory is moved I can't replay. I asked @khuey to take a look and he says it's because we don't use hardlink for execve, we only use hardlink for the shared library. There's no hardlink to the firefox binary in the replay folder.

I have this on a Digital Ocean instance at:
mozilla@mozgfx-rr-orange-hunter-1:~/orange-hunter/RROrangeHunter/untriaged/b2f49818-050a-46f5-95c2-a6cb146d794a

**Comment by bgirard** [comment]
Here's the head of the replay dump:
https://pastebin.mozilla.org/8838983

**Comment by rocallahan** [comment]
We probably should bite the bullet and fully emulate exec.

**Comment by khuey** [comment]
I looked at this briefly. Hardlinking the binary that gets execed is easy enough, but dealing with the two entries of execve on replay is annoying though.  You need to know that they're connected to avoid pulling the TraceTaskEvent, injecting the new filename, etc twice.

**Comment by luser** [comment]
Related: https://github.com/mozilla/rr/issues/1295

**Comment by rocallahan** [comment]
I was thinking of avoiding doing an execve() call at all and just emulating its effects by unmapping and remapping memory regions etc. This might be useful to help port traces between different OS (versions), since currently we just assume that execve() is deterministic.

I guess that isn't entirely possible because one of the effects of execve() is to change architectures and we can't emulate that without actually doing an exec. But we could have a couple of helper binaries that we exec instead of the real program and then emulate the rest.

**Comment by rocallahan** [comment]
I fixed this in commit 6edc031633badc4c5344151d9312fc1f58fb23d1.
