### ISSUE TITLE
Don't let the program exit when the trace is abruptly terminated

### ISSUE THREAD

**Issue by bgirard** [mozilla/rr#1626]
I've got a 60k event replay. Frequently I miss a breakpoint and get '[Inferior 1 (process 28496) exited normally]'. Because the program exited I can't reverse continue and I don't appear to be able to use checkpoints (or perhaps they're broken on my machine?).

It would be nice if RR just trapped before the program exists so that I could use 'reverse-continue' or checkpoints.

**Comment by rocallahan** [comment]
We try to do that. Recording and replaying normally issues a `SIGKILL` in the debugger when a process exits. Is this a case where you terminated rr with ctrl-C? What's at the end of the trace with `rr dump`?

**Comment by bgirard** [comment]
I think this was one of the replays where FF was hanging under RR (with FF chaos mode) so the replay is probably just a partial recording (CTRL+C'ed the hanging process on shutdown). I've since clobbered this replay. I was actually using this replay to try to debug what was happening near the end of the program to see why it was hanging on shutdown but I kept stepping too far and having the program exit so I couldn't understand why FF+RR was hanging on reftests.

**Comment by rocallahan** [comment]
If I send ctrl-C (`SIGINT`) to the recorded process, including by typing ctrl-C at the terminal (which is ignored by rr and sent to the recorded process), I see `SIGINT` and `SIGKILL` when replaying.

If I send `SIGTERM` to rr itself, rr terminates the trace abruptly (but flushes it), and during replay there's no EXIT event, and during replay we get the behavior you see here. That's fixable but a bit tricky.

Which case you get depends on the test harness since (I assume) you're running rr inside the harness, not outside it. You may be able to work around this using `kill -INT <pid-of-tracee>` instead of typing ctrl-C at the harness.

**Comment by bgirard** [comment]
Alright I'll make sure to send the signal to the right process next time. In my test script bash forks rr so it probably received the signal before the recorded process (FF). I've edited the bug to reflect the real issue. Feel free to close if this is too much of an edge case to fix.

**Comment by bgirard** [comment]
Thanks!
