### ISSUE TITLE
rr dumped trace diverges compared with strace

### ISSUE THREAD

**Issue by yjGT** [mozilla/rr#1661]
I am testing rr with a simple program (please see the following). I changed rr a bit to dereference the buf of open/read/write from the dumped trace. I am expecting to see the "open" syscall, followed by "read" or "mmap", then finally "write" to stdout. However, only the "mmap" and "write" syscalls are in the trace, the "open" syscall is missing. Are the "untraced" syscalls (e.g., open) buffered in some way that are excluded from the trace? (But I do see some "open" syscalls about shared libraries.) Am I misunderstanding the trace? Thank you!!
````
int main(){                                                                      
  int fp = 0;                                                                    
  char buf[100];                                                                 
  size_t bytes_read = 0;                                                         
                                                                                 
  fp = open("./test1.txt", O_RDONLY);                    
  bytes_read = read(fp, buf, sizeof(buf));                                       
  printf("buf: %s",buf);                                                         
                                                                                 
  close(fp);                                                                                                                                                   
  return 0;                                                                      
} 
````

**Comment by rocallahan** [comment]
`open` and `write` go through an accelerated path which we call 'syscall buffering'. Run `rr dump -b` to dump the buffered syscalls (though you don't get much information about them, because rr doesn't record much about them, for efficiency). Syscall buffering isn't activated until `librrpreload.so` is fully initialized, that's why you see some `open`s but not others.

If you need to you can disable syscall buffering using `rr record -n`.
