### ISSUE TITLE
Behavior difference with `vfork`

### ISSUE THREAD

**Issue by yuyichao** [mozilla/rr#1741]
This is simplified from libuv's `uv_spawn` implementation on linux.

```c
#include <sys/types.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

int main()
{
    volatile int err = 0;
    pid_t pid = vfork();
    if (pid == 0) {
        char *const argv[] = {"does_not_exist", NULL};
        execv(argv[0], argv);
        err = 1;
        _exit(127);
    }
    printf("%d\n", err);
    return 0;
}
```

Assuming `does_not_exist` isn't actually an existing command, the code above should print `1` when running outside rr due to the sharing of memory space in between the parent and the child process. However, this print `0` when running under rr.

This causes a test failure in julia since the exec failure is not correctly reported.

**Comment by yuyichao** [comment]
The `execv` is obviously not necessary.

```c
#include <stdio.h>
#include <unistd.h>

int main()
{
    volatile int err = 0;
    pid_t pid = vfork();
    if (pid == 0) {
        err = 1;
        printf("child: %d\n", err);
        _exit(127);
    }
    printf("parent: %d\n", err);
    return 0;
}
```

The code above prints
```
child: 1
parent: 1
```
normally and
```
child: 1
parent: 0
```
with rr. So the issue seems to be address sharing (rather than process scheduling for example...)

**Comment by yuyichao** [comment]
Actually the scheduling seems to be wrong too. Adding a `sleep(2)` before the child `printf` gives.

```
parent: 0
child: 1
```

With 2 seconds wait time between the two (running with `rr record -w`).

**Comment by rocallahan** [comment]
rr just implements vfork() as fork(). I didn't anticipate that anyone would actually rely on the sharing feature.

I suppose we could implement vfork more accurately by a) emulating vfork scheduling so that a process isn't scheduled while it has a non-execed vfork child and b) when a vfork child execs or exits, copy all its writeable data pages back to the parent.

I'm not terribly excited about implementing that.

**Comment by Keno** [comment]
`fork` is a valid implementation of `vfork`. We shouldn't be relying on this in libuv.

**Comment by rocallahan** [comment]
I suppose for performance reasons you'd only do the copy-back if the child exits without exec'ing. And hope that people aren't doing really crazy stuff. It seems like that would work in your case.

The obvious alternative would be to let vfork do a real vfork. But the weird state where you have a different pid/tgid but shared address space is a real pain to reason about. The real problem is that all our syscallbuf data is suddenly shared across processes...

**Comment by yuyichao** [comment]
> `fork` is a valid implementation of `vfork`

libuv only use this on linux, where `vfork` has defined behavior of sharing.

**Comment by Keno** [comment]
> libuv only use this on linux, where vfork has defined behavior of sharing.

That is a fair point.

**Comment by rocallahan** [comment]
I guess it might work to just lock the syscallbuf on vfork, allow the vfork, emulate vfork scheduling, and when the vfork child execs or exits unlock the syscallbuf in the parent and continue.

I can try that next week maybe.

**Comment by rocallahan** [comment]
On the recording side, that approach works well. We don't actually need to do anything with the scheduling; the scheduler observes that the kernel is keeping the vfork parent from exiting the clone()/vfork() syscall, so we don't schedule it.

On the replay side we have a problem. rr replay has an invariant that ReplayTasks are not stopped in the kernel except briefly while performing necessary syscalls. This is important because, for example, it means we can clone all tasks in a session by having them perform fork(). But when a process does a vfork() it's stuck in the kernel until the vfork child exits or execs; during that time an attempt to clone a Session would fail since we can't clone the vfork parent with fork().

**Comment by rocallahan** [comment]
We could perform a fork() instead for vfork() during replay, and then when the vfork child exits or execs sync up its address space with the vfork parent's. This is tricky to do in general if the vfork child does map/unmap/mprotect etc :-(.

**Comment by rocallahan** [comment]
Another option might be to create a thread during replay instead of doing fork or vfork. That gives the sharing behavior we want. We'd need to make sure that on execve, if the ReplayTask is a vforked child then we fork, replace the ReplayTask's real task with the forked child, kill the thread, then do the execve in the forked child. Replacing a ReplayTask's task like that would be a little bit hairy but probably doable.

**Comment by Keno** [comment]
I may be missing something but why wouldn't `clone(CLONE_VM)` work for our use case? As long as we can emulate the vfork scheduling ourselves, shouldn't that basically be the same?

**Comment by rocallahan** [comment]
If we do that, we'll probably want to lie about the task_group of the vfork ReplayTask while it's a thread, pretending it has its own task_group while it really doesn't. I don't think that would be a problem but I'm not sure. We'd probably need to introduce some way to get the real task group for a couple of places that need that --- when we need to kill all the tasks in a session, and when we need to clone the session.

**Comment by rocallahan** [comment]
> I may be missing something but why wouldn't clone(CLONE_VM) work for our use case? As long as we can emulate the vfork scheduling ourselves, shouldn't that basically be the same?

You mean during recording and replay, or just recording?

During recording we can't do that because it would mean getpid() etc give the wrong results.

**Comment by Keno** [comment]
I was thinking during replay, but I also don't see why we would get the wrong answer during recording. Could you elaborate?

**Comment by rocallahan** [comment]
Oh, I guess you mean pass CLONE_VM but not CLONE_THREAD so we get a new PID and all the rest but share the address space.

That might work. It's an exotic configuration so we might get into trouble. But probably worth trying!

**Comment by Keno** [comment]
Yes, that was the suggestion. I agree it's an exotic configuration, but from my reading of the man page the intended behavior is what we want at least.

**Comment by rocallahan** [comment]
If that works, and we use it only during replay, then scheduling is a non-issue because during replay we always follow the recorded schedule, which will have been enforced by the kernel's vfork behavior as I mentioned above.

**Comment by rocallahan** [comment]
This seems to work really well!

**Comment by rocallahan** [comment]
Thanks @Keno for the CLONE_VM idea.

**Comment by yuyichao** [comment]
Confirmed that both the C repro and the julia test failure are fixed. Thanks both of you for the idea and the fix!
