### ISSUE TITLE
Hardcoded breakpoints kill the debugged program

### ISSUE THREAD

**Issue by Ekleog** [mozilla/rr#1746]
# Context

When writing a JIT compiler, sometimes there is a need to break in a part of the code rr does not know about, given it has not been generated yet. This, for a gdb-based workflow, usually means inserting an `int 3` into the generated assembly.

# Steps to reproduce

In `a.c`, put the following content:

```c
#include <stdio.h>

int main(int argc, char** argv) {
    __asm__("int $3"); // gcc-style inline assembly
    printf("It works!\n");
    return 0;
}
```

Compile it with eg. `gcc a.c`. Then, run

    rr record a.out
    rr replay

## Expected result

`rr record` may ignore the breakpoint and display "It works!". `rr replay` should break on the breakpoint, and `continue`-ing should display "It works!".

## Actual result

`rr record` outputs nothing. `rr replay` breaks on the breakpoint but, when `continue`-ing, kills the process.

# Background

## Reason for the current behaviour

I believe `rr` tries to make running `rr record a.out` as close as possible to running `./a.out`. This means killing the process due to a breakpoint trap.

## Reasons for a change

First, there is at least one use case for this change: debugging the code produced by JIT compilers. Then, I think making `rr record a.out` closer to `gdb a.out` than to `./a.out` should not be much of an issue for other use cases: no information is lost as the sigtrap would be kept, and additional information would be gained by having an auto-`continue`

Anyway, thanks for all your work!

**Comment by rocallahan** [comment]
Thanks for the bug report!

This is already supported via `rr record --continue-through-signal=5`.

Also, for the record:
````
[10:27]	roc	I don't know how you're choosing where you want to stop, but it's pretty much always easier to know where to break *after* you've executed the code than before...
[10:28]	roc	because you have strictly more information
[10:28]	roc	e.g. if you were going to emit an int3 under some condition, you could instead just print a message with the address you were going to emit it at
````

**Comment by hotsphink** [comment]
I'm skeptical. Inserting a masm.breakpoint() is easy (it injects an "int 3" into the current position in the generated code). To print out addresses to break on, you'd need to find the base address and add it to the generator's offset, and then you'd have a set of addresses to break on, one for every instance of the generated code. Also, masm.breakpoint works with both gdb and rr.

It would be a little less mysterious if you could do rr record --continue-through-signal=TRAP, but I'm not sure how to do that other than hardcoding a list of names or code-generating from the output of kill -l or something.

The default rr record behavior is a bit surprising, too. It'd be nice if it gave some indication that it stopped due to a SIGTRAP. Also, I get an exit status of 133 (128+5) without rr record, 255 with. I can file bugs, but I don't understand the details of what is going on, so perhaps some of them are obvious WONTFIXes and I shouldn't bother?

**Comment by rocallahan** [comment]
> It would be a little less mysterious if you could do rr record --continue-through-signal=TRAP

I already have a signal list via `signal_name`. It would be easy to iterate through that list to find the number for a name. Patches accepted.

> It'd be nice if it gave some indication that it stopped due to a SIGTRAP. Also, I get an exit status of 133 (128+5) without rr record, 255 with.

Those are definitely fixable bugs. I'll take a look.

**Comment by rocallahan** [comment]
So AFAIK it's actually impossible for rr to return an exit status indicating a fatal signal unless we kill rr itself with the same signal. I guess we can do that...

**Comment by rocallahan** [comment]
But there's no point in leaving a coredump of course since it would be the wrong thing. So I'll disable coredumps for that signal.

**Comment by rocallahan** [comment]
OK, fixed that in https://github.com/mozilla/rr/commit/6baa9e4cff92c4ec29acacf40cacb2510e803810.
