### ISSUE TITLE
Possible to run strictly single threaded program without PMU virtualization support in a VM?

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#1766]
As I understand it, perf counters are used to calculate when to pre-empt a tracee thread during playback. PMU counters are also used to calculate when to deliver a UNIX signal to a tracee during playback. When running on bare metal, rr can easily access the PMU on the CPU. But when rr runs in a virtualized environment you need PMU virtualization (as I understand it only VMWare supports this properly currently). Hope my understanding is correct so far...

My question is: what if we're running rr in a virtual machine and _no_ PMU virtualization support is available _however_ the program we're recording/playing back is strictly single threaded.

Does rr work in that case? 

Ideally it should work -- rr does not need to worry about pre-empting a thread (there is only one) and I suppose UNIX signal delivery point can be calculated in some other way?

Many programs are totally single threaded and it would be very useful for rr to be able to play back/record them in virtual machine like Virtual Box which _does not_ have PMU virtualization support yet. This fallback will allow much wider distribution for rr.

Hopefully my case is already supported. If not, how difficult is it to engineer rr to support it?

**Comment by khuey** [comment]
> As I understand it, perf counters are used to calculate when to pre-empt a tracee thread during playback. PMU counters are also used to calculate when to deliver a UNIX signal to a tracee during playback.

This is true, although thread context switches are triggered under rr by an async signal, so it's really two sides of the same coin.

> When running on bare metal, rr can easily access the PMU on the CPU. But when rr runs in a virtualized environment you need PMU virtualization (as I understand it only VMWare supports this properly currently). Hope my understanding is correct so far...

KVM supports it too.  I believe it's just Virtualbox that does not.

> My question is: what if we're running rr in a virtual machine and no PMU virtualization support is available however the program we're recording/playing back is strictly single threaded.
>
> Does rr work in that case?

No

> Ideally it should work -- rr does not need to worry about pre-empting a thread (there is only one) and I suppose UNIX signal delivery point can be calculated in some other way?

As alluded to above, if you could calculate the signal delivery point some other way, you could preempt threads with it, so your "single threaded" criterion doesn't actually make the problem any more tractable.

> Many programs are totally single threaded and it would be very useful for rr to be able to play back/record them in virtual machine like Virtual Box which does not have PMU virtualization support yet. This fallback will allow much wider distribution for rr.
>
> Hopefully my case is already supported. If not, how difficult is it to engineer rr to support it?

It would be quite difficult to implement a performant alternative.  You would need to establish some sort of alternative timeline of program execution that you could refer to since the performance counters are not available.  How to do that in a way that does not require modifying the binary or singlestepping the program is not obvious.  And even if it were done, unless it were of similar speed to the native performance counter approach, I don't think we would accept patches.

**Comment by rocallahan** [comment]
> KVM supports it too. I believe it's just Virtualbox that does not.

Right. Xen does too.

Even if it could be done, I think instead of adding complexity to rr just to support single-threaded programs on VirtualBox, it would make more sense to spend that effort contributing PMU virtualization to VirtualBox.

**Comment by sidkshatriya** [comment]
Fair enough. 

I wonder why Virtualbox folks haven't made PMU virtualization a priority. I would have thought a mature virtualization platform like theirs would have it by now. Oh well.
