### ISSUE TITLE
Chromium does not get syscall buffering in render processes

### ISSUE THREAD

**Issue by khuey** [mozilla/rr#1802]
They use some sort of fork-like invocation of clone(2), which never ends up calling atfork handlers.

**Comment by khuey** [comment]
(and then never exec)

**Comment by rocallahan** [comment]
Urgh :-(.

I think after a fork or a clone(CLONE_VM | ...), instead of calling `init_thread` we can (entirely from rr) perform a new `SYS_rrcall_init_buffers` and poke the rest of the scratch-related space into the tracee. This probably means we should add to `rrcall_init_buffers_params` the addresses of the global variables involved so we can track them in `RecordTask`.

**Comment by rocallahan** [comment]
Actually, instead of tracking those variables and changing addresses, we can probably just map a new syscallbuf over the top of the old one. That's actually probably quite easy!

**Comment by khuey** [comment]
We still need new fds though.

**Comment by khuey** [comment]
Fixed by #1822
