### ISSUE TITLE
rr can't record trunk kcov

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/rr#1936]
Trying to record https://github.com/SimonKagstrom/kcov/ on a trivial c program gives:

[FATAL /home/jrmuizel/src/rr/src/record_syscall.cc:4251:rec_process_syscall_arch() errno: SUCCESS] 
 (task 13227 (rec:13227) at time 1812)
 -> Assertion `t->regs().syscall_result_signed() == -syscall_state.expect_errno' failed to hold. Expected EINVAL for 'personality' but got result 0 (errno SUCCESS)
Launch gdb with 
  gdb '-l' '10000' '-ex' 'target extended-remote :13227' /home/jrmuizel/src/kcov/build/src/kcov

**Comment by Keno** [comment]
Should be pretty easy for you to fix. Attach, gdb per instructions, figure out what value it's trying to set the personality to (or if you want you could instead strace the execution), then add the proper handling here:
https://github.com/mozilla/rr/blob/master/src/record_syscall.cc#L3779

**Comment by jrmuizel** [comment]
It's calling personality(ADDR_NO_RANDOMIZE | personality(-1))

**Comment by rocallahan** [comment]
I'll fix this. Because I love Jeff.

**Comment by rocallahan** [comment]
With this, kcov works. However, it is *incredibly* slow under rr. So it's probably mostly unusable.

**Comment by jrmuizel** [comment]
Thanks for that.

**Comment by rocallahan** [comment]
Turns out that for a very small program almost all the runtime is spent doing ptrace PEEKTEXT/POKETEXT calls, to set up the initial breakpoints I guess. Those necessarily have to be emulated by rr; we could potentially do the emulation in syscallbuf code by converting them to /proc/<pid>/mem I/O, but that would be horrible and probably not worth it just for kcov.

kcov would actually be faster, even outside rr, if those ptrace calls were converted to /proc/<pid>/mem writes --- already mentioned in https://github.com/SimonKagstrom/kcov/issues/53. Though `process_vm_writev` would be even faster on Linux (both with and without rr).

**Comment by rocallahan** [comment]
With the remix instrumentation stuff Kyle and I have, we could easily compute instruction-level coverage by instrumenting the replay. But we can't open that yet :-/.
