### ISSUE TITLE
Assertion `t->stop_sig() == SIGTRAP' failed to hold. Replay got unexpected signal (or none) 11

### ISSUE THREAD

**Issue by hotsphink** [mozilla/rr#1971]
I'm running the spidermonkey shell. I record a run that ends in an assertion failure in a helper thread. I set a breakpoint in js::Nursery::collect. When replaying, whether forward or backward, I get

Assertion `t->stop_sig() == SIGTRAP' failed to hold. Replay got unexpected signal (or none) 11

When I launch gdb with the suggested line, it says

js::Nursery::collect (this=0x7fc129572070, reason=JS::gcreason::API)
    at /home/sfink/src/mozilla2/js/src/gc/Nursery.cpp:548
548	    MOZ_ASSERT(!TlsContext.get()->suppressGC);

So it seems like it is seg faulting during replay while accessing TLS or something? Given that it's crashing in js::Nursery::collect, it seems like it hit the breakpoint. The above assertion is the first line in the body. This is not the assertion that failed during recording, and in fact is on the main thread while the actual assertion was on a helper thread.

I hit this with my old rr compile, then rebuilt rr ee20c58af947ad05b67bc27966d96248be74e365 and got the same thing.

**Comment by rocallahan** [comment]
Can you give steps to reproduce?

**Comment by hotsphink** [comment]
I tried doing various things with an unpatched JS shell, and was unable to reproduce. I pushed a try build to https://treeherder.mozilla.org/#/jobs?repo=try&revision=f121dae025979062f96f7c531795ee5aa3db2ad7 if you wanted to grab the source from there. Or if you're brave, you could grab http://people.mozilla.org/~sfink/data/js.xz and use it.

compressed sha256sum: 995ef35cf9df80e677be15092b78eec8ddac9b1488d8892e6f1d701bc5e3d4e4
uncompressed sha256sum: e4a3704862d5fff2bf9af52d0ad60d3a3af30d1a71660bb3b035c6d2d76dfdda
That was built on Fedora 24, and links against my local versions of things, so I don't know how usable it'll be.

    % rr record ./js -e 'gc(); crash()'
    % rr replay
    (rr) b js::Nursery::collect
    (rr) c
    (rr) c

This is more straightforward than my original case, and manages to stop successfully at the breakpoint the first time. But it hits the same rr assertion.

**Comment by hotsphink** [comment]
Hm, there's something weird about that binary. Running normally, it seems to be jumping into the middle of an instruction at the beginning of js::Nursery::collect.

**Comment by rocallahan** [comment]
Sorry about the delay, I had some other stuff in flight.

I can reproduce with your binary.

**Comment by rocallahan** [comment]
So:
````
(rr) b js::Nursery::collect
Breakpoint 1 at 0x107ff74: file /home/sfink/src/mozilla2/js/src/gc/Nursery.cpp, line 548.
(rr) disass 0x107ff74
Dump of assembler code for function js::Nursery::collect(JS::gcreason::Reason):
   0x000000000107ff5a <+0>:	push   %rbp
   0x000000000107ff5b <+1>:	mov    %rsp,%rbp
   0x000000000107ff5e <+4>:	push   %rbx
   0x000000000107ff5f <+5>:	sub    $0x1d8,%rsp
   0x000000000107ff66 <+12>:	mov    %rdi,-0x1c8(%rbp)
   0x000000000107ff6d <+19>:	mov    %esi,-0x1cc(%rbp)
   0x000000000107ff73 <+25>:	mov    %fs:0x0,%rax
   0x000000000107ff7c <+34>:	lea    -0x8(%rax),%rax
   0x000000000107ff83 <+41>:	mov    %rax,%rdi
...
````
So we set the breakpoint in the middle of the `mov %fs:0x0,%rax`, after the `%fs:` prefix. Then we stop there (because the prefix is just ignored when applied to the breakpoint instruction). Then we try to continue and we crash because now we're executing `mov 0x0,%rax` without the `%fs` prefix, i.e. trying to load from NULL.

**Comment by rocallahan** [comment]
So this is really a gdb or compiler bug causing the breakpoint to be set in the wrong place. I see exactly the same behavior under gdb without rr.

**Comment by rocallahan** [comment]
gdb can't really work around this because when it stops at the breakpoint, there's no robust way to know whether the `%fs:` prefix byte before the breakpoint was part the breakpoint instruction or part of the previous instruction.

rr could reverse-execute one instruction to see where that instruction ends and the next begins. Unfortunately that doesn't help in practice because rr isn't responsible for restoring the program counter after a breakpoint is hit --- gdb is.

So as far as I can tell, there's nothing we can do here. You may wish to narrow down the underlying bug and report it upstream.

**Comment by hotsphink** [comment]
I'm not completely sure I'm following. You're saying that there is an unavoidable divergence in replay, because gdb is causing it to execute differently due to the breakpoint? As in, he recorded execution continued past this point, but when running forward during the replay it hits a SIGSEGV that was not present in the original recording, due to something weird with gdb's breakpoint handling?

**Comment by rocallahan** [comment]
Yes. gdb sets a breakpoint at `0x107ff74` so the instruction at `0x107ff73` becomes `%fs: int3`. We execute up to that instruction, triggering the breakpoint with the program counter at `0x107ff75`. gdb sets the program counter to `0x107ff74` and continues. We execute `mov 0x0,%rax` instead of `mov %fs:0x0,%rax`. Boom.

**Comment by annygakh** [comment]
Hi, I have ran into the following assertion error when setting a breakpoint and replaying the trace and I figured out why it happened. After I have recorded the trace, I have since then modified some part of the code and rebuilt it. Then I have reverted the source code changes but didn't rebuild my repo for the reversion of the changes to take place in the binary. And this is when I got the assertion error when trying to replay the trace. All I had to do was to rebuild the source code. And now I can debug that trace again!
