### ISSUE TITLE
Merits of implementing rr in rust

### ISSUE THREAD

**Issue by sidkshatriya** [mozilla/rr#2181]
Disclaimer: I'm not a rust fan.

I've seen it be mentioned somewhere (on O'Callahan's blog??) that it might be a good idea to re-implement rr in rust (thought it will probably never happen).

I'm curious -- if we had infinite technical resources why would doing that be a good idea?

Another random question: would it be a good idea to implement rr in a language like golang (with c for very low level stuff). Sorry if this is a ridiculous proposition. My thought process is that it might make the already complicated C++ code base a little bit more approachable for external contributions. I'm guessing performance may not be affected too much because most of CPU time is probably going into ptrace context switching. But then again golang's own runtime may really prove to be too intrusive to running something like rr. 

Why am I asking this question? I'm wondering if it might be a good idea to port rr to another language simply as an exercise in gaining a deeper understanding of the wonderful codebase. Though I wonder if this exercise would have any intrinsic merit apart from self-education.

**Comment by rocallahan** [comment]
Disclaimer: I am a Rust fan :-).

> if we had infinite technical resources why would doing that be a good idea?

With Rust we could catch more bugs at compile time than we do with C++. For example in rr we've had bugs involving uninitialized variables (https://github.com/mozilla/rr/commit/ec3848e6e5a25305d280d5dd4d0636aa28db6628), iterator invalidation, and dangling references. Rust prevents all those. We could use Rust "unit structs" to distinguish different kinds of integers, e.g. so that rr's `FrameTime` can't be confused with other integer types. (You can do something similar with C++ wrapper structs and operator overloading but it's not ergonomic and historically compilers have not fully optimized away such wrappers.)

I would not trust the current rr implementation to handle untrusted input safely --- e.g. allow connections from untrusted gdbserver clients, or read the contents of possibly-malicious traces. Hardening the C++ implementation would at minimum require intensive fuzzing under ASAN and even then latent exploitable bugs would probably remain. With a Rust implementation we'd have very high confidence of it being free from the usual sorts of exploitable bugs.

With Rust we could use `cargo` package management to conveniently import useful Rust crates (libraries), whereas in C++ managing dependencies on external libraries is a nightmare so we just avoid it. For example I would rip out rr's custom command-line parsing and replace it with Rust's `structopt`. I would rip out rr's custom logging and replace it with `log`. We could stop vendoring `brotli` into the rr repository and just depend on the `brotli2` crate. We could probably use `xmas-elf` or `object` to replace rr's custom ELF parsing. Etc...

> would it be a good idea to implement rr in a language like golang (with c for very low level stuff).

I don't know as much about Go as I do about Rust and C++. Writing rr in Go would probably work fine and would capture some of the same advantages of writing rr in Rust. However Rust's type system is more powerful than Go's and I expect it to catch more bugs at compile time. Go's GC means we'd use roughly twice as much heap memory as a Rust or C++ implementation, which is not a big problem for rr but seems an unnecessary penalty. Otherwise the Go runtime is probably not a problem.

I honestly don't think an alternative implementation language could make rr much less complicated. The really complicated parts of rr are in the details of handling complex kernel features and they're going to be complex in any language.

> I'm wondering if it might be a good idea to port rr to another language simply as an exercise in gaining a deeper understanding of the wonderful codebase. Though I wonder if it this exercise would have any intrinsic merit apart from self-education.

If the goal is to learn about rr then I think you would achieve more by taking on a project to improve rr itself and shipping that, for example adding a feature to save persistent checkpoints for faster debugging. I'm willing to mentor the design of such features.

If the goal is to learn about software in general then rr might not be the best place to start since it's more low-level and tied to the quirks of the Linux kernel than most software out there.

**Comment by sidkshatriya** [comment]
@rocallahan Thanks for your reply. For various reasons I continue to be skeptical of Rust. I like how golang code, though it does not have many powerful abstractions, looks so "clean" and concentrates on programming logic. Rust variable lifetimes annotations make the code look so busy and complex. It should not be so tough to write linked lists in Rust  :-). Of course, these annotations do result in code that is going to be faster than a GC language. Your positive opinion of Rust makes me want to challenge my own no-so-positive one.

Long term, it may be an interesting exercise to port rr to golang. No doubt it will be a _huge_ undertaking. Its true that most of the complexity of rr arises from the intrinsic challenge of record and replay than just the use of C++. But using golang will allow access to a vast ecosystem of libraries just like Rust has and address some of the problems you mentioned above. Additionally it will put the core logic of record and replay at center stage instead of obscure C++ headaches. Here is another possibly weird question while we're on the topic: what about porting rr to swift? Swift is supposed to have amazing interop with C and is more performant than golang (but still less than Rust). The swift ecosystem is not so lively as Rust/golang though. 

But yes, I agree that if my goal is to learn the rr code base it would be better if I took on a more finite (and useful!) project than a port. 

I would like to work on the persistent checking project that you mention. 

Please fill me in on some initial information. I'm eager to start because speeding up the whole debugging experience would definitely be a great improvement.

**Comment by khuey** [comment]
We're not going to rewrite rr in rust and the other stuff became #2184 so I'm going to close this.

**Comment by alehander92** [comment]
wow the guy did rewrite rr in rust https://github.com/sidkshatriya/rd
