### ISSUE TITLE
Events used with perf_event_paranoid

### ISSUE THREAD

**Issue by roquo** [mozilla/rr#2243]
Because of security issues in our system, it is critcial to change the default for `/proc/sys/kernel/perf_event_paranoid <= 1`.
Red Hat sugggests to enable only the events, which are really used.
Could you tell me, which events we have to enable, so that we could leave the perf_event_paranoid = 2 (default in Red Hat). RR should run the same way, as if perf_event_paranoid is set to 1.

I know, we had to alter the source code, because rr checks only if perf_event_paranoid is <= 2.

Or are we unable to determine the used events, because  this is dependending on the recorded process?

**Comment by rocallahan** [comment]
> it is critcial to change the default for /proc/sys/kernel/perf_event_paranoid <= 1

You mean "it is critical NOT to change the default ..."?

The only event we need that is not available with `perf_event_paranoid` 2 is `PERF_COUNT_SW_CONTEXT_SWITCHES`.

**Comment by rocallahan** [comment]
I just discovered the `PERF_RECORD_SWITCH` feature that was created to allow detection of context switches with `perf_event_paranoid` 2. Unfortunately it doesn't fit rr well because we need the tracee to receive a signal every time it gets context-switched out. A signal is only generated when a sampled event overflows, and as far as I can tell `PERF_RECORD_SWITCH` can't trigger such overflows itself, because `PERF_RECORD_SWITCH` events are not first-class; they just come along with some other event that you're really sampling. If I enable `PERF_RECORD_SWITCH` while sampling `PERF_COUNT_SW_DUMMY` events and sampling period 1, no signal is raised even if the task enters a blocking system call and is switched out.

Potentially we could have another task polling the ring buffer looking for `PERF_RECORD_SWITCH` entries being added, and sending signals to the tracee when they arrive, but that would be much less efficient than the current approach.

**Comment by roquo** [comment]
So if I understand you correctly, if I would enable the `PERF_COUNT_SW_CONTEXT_SWTICHES` for `perf_event_paranoid` 2, then it would be the same if rr runs with `perf_event_paranoid` 1?

**Comment by rocallahan** [comment]
I think so.

**Comment by khuey** [comment]
If you can enable just the `PERF_COUNT_SW_CONTEXT_SWITCHES` event, can you document how to do that here?

**Comment by roquo** [comment]
From the red hat support:

> To work around this problem, change the value in /proc/sys/kernel/perf_event_paranoid to 1. If unable to do that, instead determine the default event used on the machine by running the ophelp -d command, and then explicitly change the end of the event from :1:1 to :0:1 to disable data collection in the kernel space, for example:
> $ operf -e CPU_CLK_UNHALTED:100000:0:0:1 true
> As a result, changing /proc/sys/kernel/perf_event_paranoid or explicitly disabling monitoring of kernel events for normal users allows collection of data, thus avoiding this issue.

I would try to do 
`$ operf -e PERF_COUNT_SW_CONTEXT_SWITCHES:100000:0:0:1 true` 
and leave `/proc/sys/kernel/perf_event_paranoid` = 2.

**Comment by rocallahan** [comment]
I don't think operf is going to help you here. That only affects oprofile.

And disabling kernel space event collection for `PERF_COUNT_SW_CONTEXT_SWITCHES` would stop the entire feature from working. So I don't think this helps.

**Comment by roquo** [comment]
Sorry, this was a misconception. Maybe there will be another way to enable specific events.
