### ISSUE TITLE
Create copy-on-write copies of mmap'd files

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/rr#602]
Currently we have a little tangle of heuristics that compute whether or not to attempt copying mmap'd files.  With at least btrfs, there's a CoW copy semantics that would let us (if cheap enough) get rid of that tangle.  So the real work here is to ensure CoW plays well with rr.

**Comment by nickolay** [comment]
For future reference:

Thanks to #1381 hard links are created in the cases where rr decided *not* to copy the file (since it's better than not copying at all) -- this should reduce the likelihood of the "system update ruined a trace" situation.

But since hardlinks are not as reliable as true CoW (will not retain a copy when writing over an existing file), the heuristics ([`should_copy_mmap_region()`](https://github.com/mozilla/rr/blob/9b624d431d237e1b91d363acfab8f3cb5f00f66d/src/util.cc#L473)) are still required.

**Comment by rocallahan** [comment]
Note that we're often unable to create hardlinks on modern Linux systems due to `fs.protected_hardlinks` being enabled.

XFS apparently supports zero-copy file copies but may be more reliable than btrfs.

**Comment by rocallahan** [comment]
We create "reflink" copies when possible. We also introduced `rr pack` to explicitly duplicate files when necessary.
